{{- if and .Values.customUser .Values.customUser.name (not .Values.customUser.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.custom-user-configname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "postgres.annotations" . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  CUSTOM_DB: {{ .Values.customUser.database | default .Values.customUser.name | b64enc | quote }}
  CUSTOM_USER: {{ .Values.customUser.name | b64enc | quote }}
  CUSTOM_PASSWORD: {{ .Values.customUser.password | default (randAlphaNum 32) | b64enc | quote }}
{{- end }}