{{- if and .Values.customUser (or .Values.customUser.name .Values.customUser.existingSecret) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-init-custom-user" (include "postgres.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "postgres.annotations" . | nindent 4 }}
  {{- end }}
data: 
  init-custom-user.sh: |
    #!/bin/sh
    
    if [ -z "$CUSTOM_DB" ] && [ -z "$CUSTOM_USER" ] && [ -z "$CUSTOM_PASSWORD" ]; then
      exit 1
    fi

    set -e

    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -v DATABASENAME="$CUSTOM_DB" -v USERNAME="$CUSTOM_USER" -v PASSWORD="'$CUSTOM_PASSWORD'" <<-EOSQL
      CREATE USER :USERNAME WITH PASSWORD :PASSWORD;
      CREATE DATABASE :DATABASENAME;
      GRANT ALL PRIVILEGES ON DATABASE :DATABASENAME TO :USERNAME;
      ALTER DATABASE :DATABASENAME OWNER TO :USERNAME;
    EOSQL
{{- end }}
