apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "postgres.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "postgres.annotations" . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "postgres.fullname" . }}-headless
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "postgres.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- $annotations := merge .Values.podAnnotations .Values.commonAnnotations }}
      {{- with $annotations }}
      annotations: {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "postgres.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "postgres.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- with (include "postgres.imagePullSecrets" .) }}
{{ . | nindent 6 }}
{{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "postgres.image" . }}
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          env:
            - name: PGDATA
              value: {{ include "postgres.dataDir" . }}/pgdata
            {{- if .Values.initdb.args }}
            - name: POSTGRES_INITDB_ARGS
              value: {{ .Values.initdb.args | quote }}
            {{- end }}
            {{- if .Values.auth.username }}
            - name: POSTGRES_USER
              value: {{ .Values.auth.username | quote }}
            {{- end }}
            {{- if .Values.auth.database }}
            - name: POSTGRES_DB
              value: {{ .Values.auth.database | quote }}
            {{- end }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "postgres.secretName" . }}
                  key: {{ .Values.auth.secretKeys.passwordKey }}
            {{- if .Values.config.postgresqlMaxConnections }}
            - name: POSTGRES_MAX_CONNECTIONS
              value: {{ .Values.config.postgresqlMaxConnections | quote }}
            {{- end }}
            {{- if .Values.config.postgresqlSharedBuffers }}
            - name: POSTGRES_SHARED_BUFFERS
              value: {{ .Values.config.postgresqlSharedBuffers | quote }}
            {{- end }}
            {{- if .Values.config.postgresqlEffectiveCacheSize }}
            - name: POSTGRES_EFFECTIVE_CACHE_SIZE
              value: {{ .Values.config.postgresqlEffectiveCacheSize | quote }}
            {{- end }}
            {{- range $key, $value := .Values.extraEnv }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- if and .Values.customUser (or .Values.customUser.name .Values.customUser.existingSecret) }}
            - name: CUSTOM_DB
              valueFrom:
                secretKeyRef:
                  {{- if .Values.customUser.existingSecret }}
                  name: {{ .Values.customUser.existingSecret }}
                  {{- else }}
                  name: {{ include "postgres.custom-user-configname" . }}
                  {{- end }}
                  {{- if .Values.customUser.secretKeys }}
                  key: {{ .Values.customUser.secretKeys.database }}
                  {{- else }}
                  key: CUSTOM_DB
                  {{- end }}
            - name: CUSTOM_USER
              valueFrom:
                secretKeyRef:
                  {{- if .Values.customUser.existingSecret }}
                  name: {{ .Values.customUser.existingSecret }}
                  {{- else }}
                  name: {{ include "postgres.custom-user-configname" . }}
                  {{- end }}
                  {{- if .Values.customUser.secretKeys }}
                  key: {{ .Values.customUser.secretKeys.name }}
                  {{- else }}
                  key: CUSTOM_USER
                  {{- end }}
            - name: CUSTOM_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if .Values.customUser.existingSecret }}
                  name: {{ .Values.customUser.existingSecret }}
                  {{- else }}
                  name: {{ include "postgres.custom-user-configname" . }}
                  {{- end }}
                  {{- if .Values.customUser.secretKeys }}
                  key: {{ .Values.customUser.secretKeys.password }}
                  {{- else }}
                  key: CUSTOM_DB
                  {{- end }}
            {{- end }}
          {{- if .Values.extraEnvVarsSecret }}
          envFrom:
            - secretRef:
                name: {{ .Values.extraEnvVarsSecret }}
          {{- end }}
          ports:
            - name: postgresql
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - |
                  pg_isready -U {{ include "postgres.username" . }} -d {{ include "postgres.database" . }} -h 127.0.0.1 -p {{ .Values.service.targetPort }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - |
                  pg_isready -U {{ include "postgres.username" . }} -d {{ include "postgres.database" . }} -h 127.0.0.1 -p {{ .Values.service.targetPort }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.startupProbe.enabled }}
          startupProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - |
                  pg_isready -U {{ include "postgres.username" . }} -d {{ include "postgres.database" . }} -h 127.0.0.1 -p {{ .Values.service.targetPort }}
            initialDelaySeconds: {{ .Values.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.startupProbe.timeoutSeconds }}
            successThreshold: {{ .Values.startupProbe.successThreshold }}
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: {{ include "postgres.dataDir" . }}
            {{- if not .Values.config.existingConfigmap }}
            - name: config
              mountPath: {{ include "postgres.configDir" . }}
            {{- end }}
            - name: run
              mountPath: {{ include "postgres.runDir" . }}
            - name: tmp
              mountPath: /tmp
            {{- if or .Values.initdb.scriptsConfigMap .Values.initdb.scripts }}
            - name: custom-init-scripts
              mountPath: /docker-entrypoint-initdb.d/
            {{- end }}
            {{- if and .Values.customUser (or .Values.customUser.name .Values.customUser.existingSecret) }}
            - name: init-custom-user
              mountPath: /docker-entrypoint-initdb.d/init-custom-user.sh
              subPath: init-custom-user.sh
            {{- end }}
      volumes:
        {{- if not .Values.persistence.enabled }}
        - name: data
          emptyDir: {}
        {{- end }}
        {{- if not .Values.config.existingConfigmap }}
        - name: config
          configMap:
            name: {{ include "postgres.configmapName" . }}
            optional: true
        {{- end }}
        - name: run
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        {{- if or .Values.initdb.scriptsConfigMap .Values.initdb.scripts }}
        - name: custom-init-scripts
          configMap:
            name: {{ include "postgres.initdb.scriptsCM" . }}
        {{- end }}
        {{- if and .Values.customUser (or .Values.customUser.name .Values.customUser.existingSecret) }}
        - name: init-custom-user
          configMap:
            name: {{ printf "%s-init-custom-user" (include "postgres.fullname" .) }}
            items:
              - key: init-custom-user.sh
                path: init-custom-user.sh
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.persistence.enabled }}
  {{- if .Values.persistentVolumeClaimRetentionPolicy.enabled }}
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: {{ .Values.persistentVolumeClaimRetentionPolicy.whenDeleted }}
    whenScaled: {{ .Values.persistentVolumeClaimRetentionPolicy.whenScaled }}
  {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: data
      {{- with .Values.persistence.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      accessModes:
        {{- range .Values.persistence.accessModes }}
        - {{ . | quote }}
        {{- end }}
      resources:
        requests:
          storage: {{ .Values.persistence.size | quote }}
      {{- if .Values.persistence.storageClass }}
      {{- if (eq "-" .Values.persistence.storageClass) }}
      storageClassName: ""
      {{- else }}
      storageClassName: {{ .Values.persistence.storageClass | quote }}
      {{- end }}
      {{- end }}
  {{- end }}
