{{- $useDeployment := and .Values.useDeployment (not .Values.persistence.enabled) -}}
{{- if and (eq .Values.architecture "replication") (not .Values.sentinel.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}-master
  namespace: {{ include "cloudpirates.namespace" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
    app.kubernetes.io/component: master
  {{- if (include "redis.annotations" .) }}
  annotations:
{{- include "cloudpirates.tplvalues.render" (dict "value" (include "redis.annotations" .) "context" .) | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.ipFamilies }}
  ipFamilies:
    {{- toYaml .Values.service.ipFamilies | nindent 4 }}
  {{- end }}
  {{- if .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.service.ipFamilyPolicy }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: redis
      protocol: TCP
      name: tcp-redis
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
    {{- range .Values.extraPorts }}
    - port: {{ .port }}
      targetPort: {{ .targetPort | default .name }}
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}
    {{- if not $useDeployment }}
    statefulset.kubernetes.io/pod-name: {{ include "redis.fullname" . }}-0
    {{- end }}
{{- end }}
