## @section Global parameters
global:
  ## @param global.imageRegistry Global Docker Image registry
  imageRegistry: ""
  ## @param global.imagePullSecrets Global Docker registry secret names as an array
  imagePullSecrets: []

## @section Common parameters
## @param nameOverride String to partially override wordpress.fullname
nameOverride: ""
## @param fullnameOverride String to fully override wordpress.fullname
fullnameOverride: ""
## @param commonLabels Labels to add to all deployed objects
commonLabels: {}
## @param commonAnnotations Annotations to add to all deployed objects
commonAnnotations: {}

## @section WordPress image parameters
image:
  ## @param image.registry WordPress image registry
  registry: docker.io
  ## @param image.repository WordPress image repository
  repository: wordpress
  ## @param image.tag WordPress image tag
  tag: "6.5.0-php8.2-apache"
  ## @param image.pullPolicy WordPress image pull policy
  pullPolicy: Always

## @param replicaCount Number of WordPress replicas to deploy
replicaCount: 1

## @section WordPress parameters
wordpress:
  ## @param wordpress.username WordPress application username
  username: user
  ## @param wordpress.password WordPress application password
  password: ""
  ## @param wordpress.email WordPress application email
  email: user@example.com
  ## @param wordpress.blogName WordPress blog name
  blogName: "WordPress Blog"
  ## @param wordpress.tablePrefix WordPress table prefix
  tablePrefix: wp_

## @param persistence.enabled Enable persistence using PVC
persistence:
  enabled: true
  ## @param persistence.storageClass PVC Storage Class
  storageClass: ""
  ## @param persistence.accessMode PVC Access Mode
  accessMode: ReadWriteOnce
  ## @param persistence.size PVC Storage Request
  size: 10Gi
  ## @param persistence.existingClaim Use an existing PVC to persist data
  existingClaim: ""

service:
  ## @param service.type Kubernetes service type
  type: ClusterIP
  ## @param service.port WordPress service port
  port: 80

## @section Ingress parameters
ingress:
  ## @param ingress.enabled Enable ingress record generation
  enabled: true
  ## @param ingress.className IngressClass that will be be used to implement the Ingress
  className: nginx
  ## @param ingress.annotations Additional annotations for the Ingress resource
  annotations: {}
  ## @param ingress.hosts An array with hosts and paths
  hosts:
    - host: wordpress.localhost
      paths:
        - path: /
          pathType: ImplementationSpecific
  ## @param ingress.tls An array with the tls configuration
  tls: []

## @section Service Account parameters
serviceAccount:
  ## @param serviceAccount.create Specifies whether a service account should be created
  create: true
  ## @param serviceAccount.annotations Annotations to add to the service account
  annotations: {}
  ## @param serviceAccount.name The name of the service account to use
  name: ""
  ## @param serviceAccount.automountServiceAccountToken Automatically mount service account token
  automountServiceAccountToken: false

## @param resources Resource limits and requests for WordPress pod
resources:
  {}
  ## We usually recommend not to specify default resources and to leave this as a conscious
  ## choice for the user. This also increases chances charts run on environments with little
  ## resources, such as Minikube. If you do want to specify resources, uncomment the following
  ## lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   memory: 256Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

## @param nodeSelector Node selector for pod assignment
nodeSelector: {}

## @param tolerations Tolerations for pod assignment
tolerations: []

## @param affinity Affinity rules for pod assignment
affinity: {}

## @param containerSecurityContext Security context for the container
containerSecurityContext:
  runAsNonRoot: true
  runAsUser: 33
  allowPrivilegeEscalation: false

## @param podSecurityContext Security context for the pod
podSecurityContext:
  fsGroup: 33

## @section MariaDB parameters
## MariaDB chart configuration
mariadb:
  ## @param mariadb.enabled Whether to use the MariaDB chart
  enabled: true
  ## @param mariadb.auth.rootPassword MariaDB root password
  auth:
    rootPassword: ""
    ## @param mariadb.auth.database MariaDB custom database
    database: wordpress
    ## @param mariadb.auth.username MariaDB custom user name
    username: wordpress
    ## @param mariadb.auth.password MariaDB custom user password
    password: "changeme"

## @section Probes Configuration
livenessProbe:
  ## @param livenessProbe.enabled Enable livenessProbe
  enabled: true
  ## @param livenessProbe.initialDelaySeconds Initial delay seconds for livenessProbe
  initialDelaySeconds: 120
  ## @param livenessProbe.periodSeconds Period seconds for livenessProbe
  periodSeconds: 10
  ## @param livenessProbe.timeoutSeconds Timeout seconds for livenessProbe
  timeoutSeconds: 5
  ## @param livenessProbe.failureThreshold Failure threshold for livenessProbe
  failureThreshold: 6
  ## @param livenessProbe.successThreshold Success threshold for livenessProbe
  successThreshold: 1

readinessProbe:
  ## @param readinessProbe.enabled Enable readinessProbe
  enabled: true
  ## @param readinessProbe.initialDelaySeconds Initial delay seconds for readinessProbe
  initialDelaySeconds: 30
  ## @param readinessProbe.periodSeconds Period seconds for readinessProbe
  periodSeconds: 10
  ## @param readinessProbe.timeoutSeconds Timeout seconds for readinessProbe
  timeoutSeconds: 5
  ## @param readinessProbe.failureThreshold Failure threshold for readinessProbe
  failureThreshold: 6
  ## @param readinessProbe.successThreshold Success threshold for readinessProbe
  successThreshold: 1

## @param extraEnv Additional environment variables to set
extraEnv: []
# - name: WORDPRESS_CONFIG_EXTRA
#   value: "define('WP_MEMORY_LIMIT', '256M');"

## @param extraVolumes Additional volumes to add to the pod
extraVolumes: []

## @param extraVolumeMounts Additional volume mounts to add to the WordPress container
extraVolumeMounts: []

## @param extraObjects Array of extra objects to deploy with the release
extraObjects: []
