apiVersion: v2
name: zookeeper
description: Apache ZooKeeper is a centralized service for maintaining configuration information, naming, providing distributed synchronization, and providing group services.
type: application
version: 0.1.1
appVersion: "3.9.2"
keywords:
  - zookeeper
  - distributed
  - coordination
  - apache
home: https://zookeeper.apache.org/
sources:
  - https://github.com/apache/zookeeper
annotations:
  category: Database
  license: Apache-2.0
maintainers:
  - name: CloudPirates GmbH & Co. KG
    url: https://www.cloudpirates.io
  - name: Gianni Carafa
    email: gianni.carafa@srf.ch
    url: https://www.srf.ch
dependencies:
  - name: common
    version: "1.x.x"
    repository: oci://registry-1.docker.io/cloudpirates
icon: https://a.storyblok.com/f/143071/512x512/07b0f90b58/apache-zookeeper-logo.svg
